development:
  database: mycity_dev
  raise_not_found_error: false
  allow_dynamic_fields: false

test:
  database: mycity_test
  raise_not_found_error: false
  allow_dynamic_fields: false

production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>

